<a href="https://colab.research.google.com/github/gradedSystem/Road_safety_scraper/blob/main/Road_Safety_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import re

URL = "https://en.wikipedia.org/wiki/Road_safety_in_Europe"
page = requests.get(URL)
soup = BeautifulSoup(page.content, "html.parser")

def clean(text):
  cleaner = re.compile('<.*?>|.*?\((.*?)\)|[\(\[].*?[\)\]]')
  cleantext = re.sub(cleaner, '', text)
  return cleantext.strip('\n')

values = soup.find_all('table')[2].find_all('tr')
j = 0
table_results = []
column_names = []
for i in values[1:]:
  """Get all the values in the table, 
  clean from html tags and add to overall results"""
  results = i.find_all('td')
  new_list = []
  n = 0
  for j in results[:-2]:
    if n == 1:
      new_list.append('2018')
      new_list.append(clean(str(j)))
      n+=1 
    else:
      new_list.append(clean(str(j)))
      n+=1
  table_results.append(new_list)

for i in values:
  """Column names"""
  col_results = i.find_all('th')
  n = 0
  for j in col_results[:-2]:
    if n == 1:
      column_names.append('Year')
      column_names.append(clean(str(j)))
      n+=1
    else:
      column_names.append(clean(str(j)))
      n+=1
  break

data = pd.DataFrame(table_results,columns=column_names)
data.head()

    Country  ... Road deaths\nper Million Inhabitants in 2018
0   Austria  ...                                           45
1   Belgium  ...                                           52
2  Bulgaria  ...                                           88
3   Croatia  ...                                           77
4    Cyprus  ...                                           57

[5 rows x 10 columns]